version: '3.8'

services:
  farmgrid-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: farmgrid-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8005:3333"
    restart: always
    env_file:
      - .env
    environment:
      - APP_NAME=FarmGrid
      - PORT=3333
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
      - ENEZA_SMS_API_KEY=${ENEZA_SMS_API_KEY}
      - ENEZA_SMS_PARTNER_ID=${ENEZA_SMS_PARTNER_ID}
      - ENEZA_SMS_SHORTCODE=${ENEZA_SMS_SHORTCODE}
      - ENEZA_SMS_API_URL=${ENEZA_SMS_API_URL}
      - ENEZA_SMS_BULK_API_URL=${ENEZA_SMS_BULK_API_URL}
      - TEST_SMS_PHONE=${TEST_SMS_PHONE}

  farmgrid-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: farmgrid-web
    ports:
      - "8007:5173"
    restart: always
    depends_on:
      - farmgrid-backend
    env_file:
      - .env
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_AUTH_TOKEN_KEY=${VITE_AUTH_TOKEN_KEY}
      - VITE_USER_KEY=${VITE_USER_KEY}
      - VITE_APP_NAME=${VITE_APP_NAME}
      - VITE_APP_LOGO=${VITE_APP_LOGO}
      - VITE_ENABLE_ANALYTICS=${VITE_ENABLE_ANALYTICS}
      - VITE_ENABLE_PWA=${VITE_ENABLE_PWA}
